name: your_app_name
description: A new Flutter project with enhanced features and UI.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.7.1
  firebase_messaging: ^14.6.1
  google_sign_in: ^6.1.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  flutter_local_notifications: ^17.2.2
  google_fonts: ^4.0.4
  lottie: ^2.3.2
  fl_chart: ^0.69.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - assets/animations/
  #   - assets/images/