// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5d6BswymE0Pd7SAjA0THoc5GrAHNa0gI',
    appId: '1:77637251215:web:86585529cb10d6818e80fa',
    messagingSenderId: '77637251215',
    projectId: 'rbuy-4310a',
    authDomain: 'rbuy-4310a.firebaseapp.com',
    storageBucket: 'rbuy-4310a.appspot.com',
    measurementId: 'G-DW4H98VN82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHwBowmuU3F5UwZ0kDj4KmVTIqC3U22vo',
    appId: '1:77637251215:android:1af0b7300e81da2d8e80fa',
    messagingSenderId: '77637251215',
    projectId: 'rbuy-4310a',
    storageBucket: 'rbuy-4310a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Ryj5tEju_ZvSXbuyNpdvpebmFlGuHhM',
    appId: '1:77637251215:ios:38040322898a173b8e80fa',
    messagingSenderId: '77637251215',
    projectId: 'rbuy-4310a',
    storageBucket: 'rbuy-4310a.appspot.com',
    iosBundleId: 'com.Rbuy.rbuyNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Ryj5tEju_ZvSXbuyNpdvpebmFlGuHhM',
    appId: '1:77637251215:ios:38040322898a173b8e80fa',
    messagingSenderId: '77637251215',
    projectId: 'rbuy-4310a',
    storageBucket: 'rbuy-4310a.appspot.com',
    iosBundleId: 'com.Rbuy.rbuyNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5d6BswymE0Pd7SAjA0THoc5GrAHNa0gI',
    appId: '1:77637251215:web:44828339bbac711f8e80fa',
    messagingSenderId: '77637251215',
    projectId: 'rbuy-4310a',
    authDomain: 'rbuy-4310a.firebaseapp.com',
    storageBucket: 'rbuy-4310a.appspot.com',
    measurementId: 'G-VTXQS5G5J5',
  );
}
